name: simple_bank
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_screenutil: ^5.9.0
  fpdart: ^1.1.0
  get_it: ^7.7.0
  go_router: ^14.0.2
  http: ^1.2.1
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  top_snackbar: ^0.0.6
  top_snackbar_flutter: ^3.1.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
